spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DB}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      globally_quoted_identifiers: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    async:
      request-timeout: 3600000
server:
  port: 8000